export const getCouponsResp = {
  data: {
    error: 0,
    success: true,
    record_count: 4,
    records: [
      {
        storeid: 111,
        sale_id: 1,
        sale_date: "2026-01-01T00:00:00",
        store_name: "IGA 1",
        store_number: "1",
        product_code: null,
        product_description: "CPN: Meat",
        is_coupon: 1,
        coupon_amount: 10,
        vendor_coupon: 10,
        store_coupon: 0,
        coupon_type: "vendor",
        sale_type: "Sale",
        line_number: 8,
        cashier_number: 49,
        cashier_name: "Karmyn",
        employee_number: null,
        terminal: "2",
        qty: 0,
        total_sales: 0,
        sub_department: 9,
        sub_department_description: "Meat",
        category: 0,
        category_description: "",
        customer_id: "",
        customer_name: "",
      },
      {
        storeid: 111,
        sale_id: 2,
        sale_date: "2026-01-02T00:00:00",
        store_name: "IGA 1",
        store_number: "1",
        product_code: null,
        product_description: "CPN: Grocery",
        is_coupon: 1,
        coupon_amount: 5.99,
        vendor_coupon: 5.99,
        store_coupon: 0,
        coupon_type: "vendor",
        sale_type: "Sale",
        line_number: 3,
        cashier_number: 32,
        cashier_name: "Jessica",
        employee_number: null,
        terminal: "2",
        qty: 0,
        total_sales: 0,
        sub_department: 1,
        sub_department_description: "Grocery",
        category: 0,
        category_description: "",
        customer_id: "",
        customer_name: "",
      },
      {
        storeid: 111,
        sale_id: 3,
        sale_date: "2026-01-01T00:00:00",
        store_name: "IGA 1",
        store_number: "1",
        product_code: "7111714426.0",
        product_description: "CPN: RSR SIGN MASH POT 24 OZ",
        is_coupon: 1,
        coupon_amount: 1,
        vendor_coupon: 1,
        store_coupon: 0,
        coupon_type: "vendor",
        sale_type: "Sale",
        line_number: 15,
        cashier_number: 49,
        cashier_name: "Karmyn",
        employee_number: null,
        terminal: "2",
        qty: 0,
        total_sales: 0,
        sub_department: 9,
        sub_department_description: "Meat",
        category: 58023,
        category_description: "SIDE DISHES",
        customer_id: "",
        customer_name: "",
      },
      {
        storeid: 111,
        sale_id: 4,
        sale_date: "2026-01-02T00:00:00",
        store_name: "IGA 1",
        store_number: "2",
        product_code: "84037090312.0",
        product_description: "CPN: KR GRTED PARM PP4.99 8 OZ",
        is_coupon: 1,
        coupon_amount: 0.5,
        vendor_coupon: 0.5,
        store_coupon: 0,
        coupon_type: "vendor",
        sale_type: "Sale",
        line_number: 6,
        cashier_number: 53,
        cashier_name: "BROOKLYN",
        employee_number: null,
        terminal: "3",
        qty: 0,
        total_sales: 0,
        sub_department: 6,
        sub_department_description: "Dairy",
        category: 50004,
        category_description: "GRATED CHEESE",
        customer_id: "",
        customer_name: "",
      },
      {
        storeid: 111,
        sale_id: 189237,
        sale_date: "2026-01-04T00:00:00",
        store_name: "IGA 1",
        store_number: "1",
        product_code: "2100002649.0",
        product_description: "CPN: KR MIRACLE WHIP 30 OZ",
        is_coupon: 1,
        coupon_amount: 0.5,
        vendor_coupon: 0.5,
        store_coupon: 0,
        coupon_type: "vendor",
        sale_type: "Sale",
        line_number: 2,
        cashier_number: 141,
        cashier_name: "Tracy F.",
        employee_number: null,
        terminal: "2",
        qty: 0,
        total_sales: 0,
        sub_department: 1,
        sub_department_description: "Grocery",
        category: 30001,
        category_description: "WHIPPED SALAD DRESSING",
        customer_id: "1234",
        customer_name: "",
      },
    ],
  },
};

export const getTransResp = {
  data: {
    error: 0,
    success: true,
    transaction: [
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 1,
        terminal: "2",
        total_sales: 1.99,
        net_sales: 1.99,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "27002500000",
        product_description: "Managers Special - WIC Produce EA 1 EA",
        price_type: "REG",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: "RHC",
        size: "1 EA",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 2,
        terminal: "2",
        total_sales: 2.12,
        net_sales: 2.0,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "1341356241",
        product_description: "TWIX XMAS BARK 4 OZ",
        price_type: "TPR",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: "CHRISTMAS",
        size: "4 OZ",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 3,
        terminal: "2",
        total_sales: 2.12,
        net_sales: 2.0,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "1341352411",
        product_description: "SNICKER XMAS BARK 4 OZ",
        price_type: "TPR",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: "CHRISTMAS",
        size: "4 OZ",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 4,
        terminal: "2",
        total_sales: 3.1700000000000004,
        net_sales: 2.99,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "7726004138",
        product_description: "RS MC PECAN DELIGHT BOX 8.1 OZ",
        price_type: "TPR",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: null,
        size: "8.1 OZ",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 5,
        terminal: "2",
        total_sales: 0.59,
        net_sales: 0.59,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "7248600220",
        product_description: "JIFFY CORN MUFFIN MIX 8.5 OZ",
        price_type: "TPR",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: null,
        size: "8.5 OZ",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 6,
        terminal: "2",
        total_sales: 0.59,
        net_sales: 0.59,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "7248600220",
        product_description: "JIFFY CORN MUFFIN MIX 8.5 OZ",
        price_type: "TPR",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: null,
        size: "8.5 OZ",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 7,
        terminal: "2",
        total_sales: 9.49,
        net_sales: 9.49,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "9004688590",
        product_description: "FISCHER BOLO QUART 22 OZ",
        price_type: "REG",
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: null,
        size: "22 OZ",
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 10.0,
        is_coupon: 1,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Sale",
        sale_date: "2026-01-01T00:00:00",
        line_number: 8,
        terminal: "2",
        total_sales: 0.0,
        net_sales: 10.0,
        qty: 0.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: null,
        product_description: "CPN: Meat",
        price_type: null,
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: null,
        size: null,
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 1.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
      {
        storeid: 111,
        coupon_amount: 0.0,
        is_coupon: 0,
        store_name: "IGA 1",
        store_number: "1",
        sale_type: "Tender",
        sale_date: "2026-01-01T00:00:00",
        line_number: 9,
        terminal: "2",
        total_sales: 10.07,
        net_sales: 10.07,
        qty: 1.0,
        weight: 0.0,
        sale_id: "111-188827-2-1-1-2026",
        product_code: "Tender",
        product_description: "Debit card",
        price_type: null,
        store_city: "Glasgow",
        store_state: "KY",
        store_zipcode: null,
        store_phone: "270-651-7577",
        store_address: null,
        brand: null,
        size: null,
        is_discounted: 0,
        cashier_number: 49,
        cashier_name: "Karmyn",
        sale_start_time: "155327",
        sale_end_time: "155631",
        fs: 0.0,
        fsa: 0.0,
        wic: 0.0,
        scalable: 0,
      },
    ],
  },
};
