import type { User } from "../../../interfaces";

export const fakeUsers: User[] = [
  {
    id: 1,
    username: "testuser2",
    email: "",
    first_name: "Test",
    last_name: "User2",
    role: 1,
    user_level: 4,
    company: 2,
    active: 1,
    join_date: "2023-01-02",
    last_visit: "2023-01-11",
    logged_in: false,
    security: 0,
    password: "",
    template: null,
    password_change_needed: 0,
    security_question_id: 0,
    security_answer: "",
  },
  {
    id: 1,
    username: "testuser2",
    email: "",
    first_name: "Test",
    last_name: "User2",
    role: 1,
    user_level: 4,
    company: 2,
    active: 1,
    join_date: "2023-01-02",
    last_visit: "2023-01-11",
    logged_in: false,
    security: 0,
    password: "",
    template: null,
    password_change_needed: 0,
    security_question_id: 0,
    security_answer: "",
  },
  {
    id: 1,
    username: "testuser2",
    email: "",
    first_name: "Test",
    last_name: "User2",
    role: 1,
    user_level: 4,
    company: 2,
    active: 1,
    join_date: "2023-01-02",
    last_visit: "2023-01-11",
    logged_in: false,
    security: 0,
    password: "",
    template: null,
    password_change_needed: 0,
    security_question_id: 0,
    security_answer: "",
  },
  {
    id: 1,
    username: "testuser2",
    email: "",
    first_name: "Test",
    last_name: "User2",
    role: 1,
    user_level: 4,
    company: 2,
    active: 1,
    join_date: "2023-01-02",
    last_visit: "2023-01-11",
    logged_in: false,
    security: 0,
    password: "",
    template: null,
    password_change_needed: 0,
    security_question_id: 0,
    security_answer: "",
  },
];