import { useAppSelector, useAppDispatch } from "../../hooks";

export const useCashierCtx = () => {
  const dispatch = useAppDispatch();
  const { url, miktoUrl, apiKey, token, isMobile, isTablet } = useAppSelector(
    (state) => state.app,
  );
  const {
    storeCards,
    cashierCards,
    stores,
    cashiers,
    selectedStoreCard,
    dataView,
    loadingStores,
    loadingCashiers,
    cashierFilterType,
    cashierFilterModalOpen,
    cashierNameFilter,
    exceptionTierFilter,
    riskLevelFilter,
    totalSalesFilter,
    totalQtyFilter,
    storeNameFilter,
    cashNameFilterApplied,
    storeNameFilterApplied,
    totalSalesFilterApplied,
    totalQtyFilterApplied,
    applyFilters,
    exceptionTierFilterApplied,
    riskLevelFilterApplied,
    filteredCashierCards,
    filteredStoreCards,
    exceptionQtyTypes,
    exceptionSalesTypes,
    transList,
    exportModalOpen,
    noRowsFound,
    fetchingTransactions,
    transCashNameFilter,
    transDateFilter,
    transDescFilter,
    transUpcFilter,
    transTotalSalesFilter,
    transFilterModalOpen,
    selectedTransFilter,
    applyTransFilters,
    filteredTransList,
    noStoresFound,
    transOverviews,
    filteredTransOverviews,
    transTotalQtyFilter,
    transactionLoadingMessage,
  } = useAppSelector((state) => state.cashier);
  const { startDate, endDate, type, lastStore, lastGroup } = useAppSelector(
    (state) => state.search,
  );
  const { userid } = useAppSelector((state) => state.user);

  return {
    apiKey,
    applyFilters,
    cashierCards,
    cashierFilterModalOpen,
    cashierFilterType,
    cashierNameFilter,
    cashNameFilterApplied,
    exportModalOpen,
    storeNameFilterApplied,
    totalSalesFilterApplied,
    totalQtyFilterApplied,
    exceptionSalesTypes,
    exceptionTierFilterApplied,
    exceptionQtyTypes,
    filteredTransOverviews,
    riskLevelFilterApplied,
    cashiers,
    dataView,
    dispatch,
    endDate,
    exceptionTierFilter,
    filteredCashierCards,
    filteredStoreCards,
    lastGroup,
    lastStore,
    loadingCashiers,
    loadingStores,
    miktoUrl,
    riskLevelFilter,
    selectedStoreCard,
    startDate,
    storeCards,
    storeNameFilter,
    stores,
    token,
    totalSalesFilter,
    totalQtyFilter,
    transList,
    type,
    url,
    userid,
    noRowsFound,
    fetchingTransactions,
    transCashNameFilter,
    transDateFilter,
    transDescFilter,
    transUpcFilter,
    transTotalSalesFilter,
    transFilterModalOpen,
    selectedTransFilter,
    applyTransFilters,
    filteredTransList,
    noStoresFound,
    transOverviews,
    transTotalQtyFilter,
    transactionLoadingMessage,
    isMobile,
    isTablet,
  };
};
