import type { FileSpec, RecordSpec } from "../../core/types";

/**
 * The AWG QBP539 electronic-invoice layout, as configuration.
 *
 * Nine record types, 134 fields, every record exactly 204 characters. Offsets
 * are **1-indexed and inclusive**, matching the vendor's published layout so
 * this file can be read against the spec sheet line by line. `core/fixedWidth`
 * is the only thing that converts them.
 *
 * Adding or correcting a field is an edit here and nowhere else — no engine
 * branches on any of these names.
 */

const RECORDS: RecordSpec[] = [
  {
    code: "01",
    name: "Detail billed item",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "delv_date", start: 17, end: 24, type: "date" },
      {
        name: "case_qty_billed",
        start: 25,
        end: 29,
        type: "signed",
        decimals: 0,
      },
      {
        name: "cost_ext",
        start: 30,
        end: 42,
        type: "signed",
        decimals: 2,
        desc: "Extended net cost",
      },
      { name: "deferd_bill_date", start: 43, end: 50, type: "date" },
      { name: "deferd_bill_flag", start: 51, end: 51, type: "text" },
      { name: "upc_code", start: 52, end: 66, type: "id" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      { name: "item_code_bil", start: 71, end: 76, type: "id" },
      { name: "item_code_ord", start: 77, end: 82, type: "id" },
      { name: "sub_code", start: 83, end: 83, type: "text" },
      { name: "item_desc", start: 88, end: 110, type: "text" },
      {
        name: "ba_retail_ext",
        start: 111,
        end: 118,
        type: "signed",
        decimals: 2,
        desc: "Extended retail",
      },
      {
        name: "rwi",
        start: 119,
        end: 119,
        type: "text",
        desc: "Random weight indicator",
      },
      { name: "picking_slot", start: 121, end: 126, type: "text" },
      { name: "size", start: 127, end: 132, type: "text" },
      { name: "pack", start: 133, end: 137, type: "signed", decimals: 0 },
      {
        name: "retail_pricing_unit",
        start: 138,
        end: 140,
        type: "signed",
        decimals: 0,
      },
      {
        name: "retail_price",
        start: 141,
        end: 147,
        type: "signed",
        decimals: 2,
      },
      {
        name: "mbr_case_cost",
        start: 148,
        end: 154,
        type: "signed",
        decimals: 2,
      },
      {
        name: "mbr_ext_case_cost",
        start: 155,
        end: 163,
        type: "signed",
        decimals: 2,
      },
      { name: "freight", start: 164, end: 168, type: "signed", decimals: 2 },
      {
        name: "pallet_weight",
        start: 169,
        end: 173,
        type: "signed",
        decimals: 2,
      },
      { name: "deal_seqnum", start: 174, end: 179, type: "id" },
      { name: "order_qty", start: 188, end: 192, type: "signed", decimals: 0 },
      { name: "item_rfrnc_cd", start: 195, end: 204, type: "text" },
    ],
  },
  {
    code: "02",
    name: "Detail deal / allowance",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "delv_date", start: 17, end: 24, type: "date" },
      {
        name: "case_qty_billed",
        start: 25,
        end: 29,
        type: "signed",
        decimals: 0,
      },
      { name: "upc_code", start: 52, end: 66, type: "id" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      { name: "item_code_bil", start: 71, end: 76, type: "id" },
      { name: "item_code_ord", start: 77, end: 82, type: "id" },
      { name: "sub_code", start: 83, end: 83, type: "text" },
      { name: "offer_cd", start: 88, end: 94, type: "id", desc: "Deal number" },
      { name: "start_date", start: 97, end: 104, type: "date" },
      { name: "end_date", start: 105, end: 112, type: "date" },
      {
        name: "deal_amount",
        start: 114,
        end: 120,
        type: "signed",
        decimals: 2,
        desc: "Extended deal $",
      },
      { name: "size", start: 127, end: 132, type: "text" },
      { name: "deal_seqnum", start: 174, end: 179, type: "id" },
      { name: "promo_id", start: 180, end: 182, type: "text" },
    ],
  },
  {
    code: "03",
    name: "Pallet / case-eligible allowance",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "delv_date", start: 17, end: 24, type: "date" },
      {
        name: "case_qty_billed",
        start: 25,
        end: 29,
        type: "signed",
        decimals: 0,
      },
      { name: "upc_code", start: 52, end: 66, type: "id" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      { name: "item_code_bil", start: 71, end: 76, type: "id" },
      { name: "item_code_ord", start: 77, end: 82, type: "id" },
      { name: "sub_code", start: 83, end: 83, type: "text" },
      { name: "item_desc", start: 88, end: 110, type: "text" },
      {
        name: "ba_retail_ext",
        start: 114,
        end: 120,
        type: "signed",
        decimals: 2,
        desc: "Full pallet allowance amount",
      },
      { name: "size", start: 127, end: 132, type: "text" },
      { name: "deal_seqnum", start: 174, end: 179, type: "id" },
    ],
  },
  {
    code: "04",
    name: "Tax",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "upc_code", start: 52, end: 66, type: "id" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      { name: "item_code_bil", start: 71, end: 76, type: "id" },
      { name: "item_code_ord", start: 77, end: 82, type: "id" },
      {
        name: "location_code",
        start: 83,
        end: 88,
        type: "text",
        desc: "State/county/city taxing code",
      },
      { name: "tax_type", start: 89, end: 91, type: "text" },
      { name: "tax_amount", start: 92, end: 97, type: "signed", decimals: 2 },
    ],
  },
  {
    code: "05",
    name: "Order exception",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "delv_date", start: 17, end: 24, type: "date" },
      {
        name: "case_qty_billed",
        start: 25,
        end: 29,
        type: "signed",
        decimals: 0,
      },
      { name: "upc_code", start: 52, end: 66, type: "id" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      { name: "item_code_bil", start: 71, end: 76, type: "id" },
      { name: "item_code_ord", start: 77, end: 82, type: "id" },
      { name: "sub_code", start: 83, end: 83, type: "text" },
      { name: "item_desc", start: 84, end: 110, type: "text" },
      {
        name: "ba_retail_ext",
        start: 111,
        end: 118,
        type: "signed",
        decimals: 2,
      },
      { name: "picking_slot", start: 121, end: 126, type: "text" },
      { name: "size", start: 127, end: 132, type: "text" },
      {
        name: "retail_price",
        start: 141,
        end: 147,
        type: "signed",
        decimals: 2,
      },
      {
        name: "excpt_desc",
        start: 148,
        end: 177,
        type: "text",
        desc: "Reason product did not ship",
      },
      { name: "bll_nxt_avl_dt", start: 188, end: 195, type: "date" },
      { name: "dsc_dt", start: 196, end: 203, type: "date" },
    ],
  },
  {
    code: "06",
    name: "Shipper component",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "upc_code", start: 52, end: 66, type: "id" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      { name: "shipper_item_code_bil", start: 71, end: 76, type: "id" },
      { name: "shipper_item_code_ord", start: 77, end: 82, type: "id" },
      { name: "component_item_code", start: 83, end: 88, type: "id" },
      { name: "item_desc", start: 89, end: 111, type: "text" },
      { name: "size", start: 112, end: 117, type: "text" },
      { name: "component_upc", start: 118, end: 132, type: "id" },
      {
        name: "retail_pricing_unit",
        start: 133,
        end: 139,
        type: "signed",
        decimals: 0,
      },
      { name: "cost", start: 140, end: 148, type: "signed", decimals: 2 },
      { name: "quantity", start: 149, end: 153, type: "signed", decimals: 0 },
    ],
  },
  {
    code: "11",
    name: "Delivery charge",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "delv_date", start: 17, end: 24, type: "date" },
      {
        name: "cost_ext",
        start: 30,
        end: 42,
        type: "signed",
        decimals: 2,
        desc: "Total delivery fees",
      },
      { name: "deferd_bill_date", start: 43, end: 50, type: "date" },
      { name: "deferd_bill_flag", start: 51, end: 51, type: "text" },
    ],
  },
  {
    code: "19",
    name: "Invoice total",
    fields: [
      { name: "store_nbr", start: 3, end: 6, type: "id" },
      { name: "invoice_nbr", start: 7, end: 13, type: "id" },
      { name: "retail_dept", start: 14, end: 16, type: "id" },
      { name: "delv_date", start: 17, end: 24, type: "date" },
      {
        name: "case_qty_billed",
        start: 25,
        end: 29,
        type: "signed",
        decimals: 0,
        desc: "Total cases",
      },
      {
        name: "cost_ext",
        start: 30,
        end: 42,
        type: "signed",
        decimals: 2,
        desc: "Extended cost, deals netted",
      },
      { name: "deferd_bill_date", start: 43, end: 50, type: "date" },
      { name: "deferd_bill_flag", start: 51, end: 51, type: "text" },
      { name: "facility", start: 67, end: 68, type: "id" },
      { name: "whse", start: 69, end: 70, type: "id" },
      {
        name: "deal_amount",
        start: 114,
        end: 120,
        type: "signed",
        decimals: 2,
        desc: "Grand total allowances",
      },
      {
        name: "mbr_ext_case_cost",
        start: 155,
        end: 163,
        type: "signed",
        decimals: 2,
      },
      { name: "total_fees", start: 164, end: 168, type: "signed", decimals: 2 },
      {
        name: "total_retail",
        start: 180,
        end: 187,
        type: "signed",
        decimals: 2,
      },
      {
        name: "total_perf_allow",
        start: 188,
        end: 194,
        type: "signed",
        decimals: 2,
      },
    ],
  },
  {
    code: "99",
    name: "File total count",
    fields: [
      { name: "str_nbr", start: 3, end: 6, type: "text" },
      { name: "inv_nbr", start: 7, end: 13, type: "text" },
      {
        name: "rec_cnt",
        start: 14,
        end: 19,
        type: "int",
        desc: "Records in file, excluding this one",
      },
      { name: "date_created", start: 20, end: 27, type: "date" },
      {
        name: "time_created",
        start: 28,
        end: 33,
        type: "text",
        desc: "HHMMSS",
      },
    ],
  },
];

export const AWG_FILE_SPEC: FileSpec = {
  recordLength: 204,
  recordTypeLength: 2,
  schemas: Object.fromEntries(RECORDS.map((r) => [r.code, r])),
};

/** Record types, named for readability at the call sites that group them. */
export const AWG_RECORD = {
  lineItem: "01",
  deal: "02",
  palletAllowance: "03",
  tax: "04",
  exception: "05",
  shipperComponent: "06",
  deliveryCharge: "11",
  invoiceTotal: "19",
  fileTrailer: "99",
} as const;
