export const baseGroupResp = {
  error: 0,
  success: true,
  groups: [
    {
      id: 59,
      name: "Simple Test",
      active: 1,
    },
    {
      id: 1,
      name: "TEST GROUP",
      active: 1,
    },
    {
      id: 41,
      name: "Test Portal group",
      active: 0,
    },
    {
      id: 28,
      name: "Test Restaraunt",
      active: 0,
    },
  ],
};

export const allUsersResp = {
  error: 0,
  success: true,
  msg: "Success",
  users: [
    {
      id: 1,
      username: "test1",
      password: "SomeR@ndomPassword123!",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "one",
      last_name: "test",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: 1,
      role: 5,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 2,
      username: "test2",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "two",
      last_name: "fake",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 3,
      username: "test3",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "three",
      last_name: "example",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: 1,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 4,
      username: "test4",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "four",
      last_name: "notreal",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 5,
      username: "test5",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "five",
      last_name: "who",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 6,
      username: "test6",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "six",
      last_name: "Jenkins",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
  ],
};

export const updateUserResp = {
  error: 0,
  success: true,
  msg: "User updated successfully",
};

export const deleteUpdateBaseGroupLinkResp = {
  error: 0,
  success: true,
};

export const defaultResp = { error: 0 };

export const userStoresResp = {
  error: 0,
  success: true,
  all_stores_for_user: [],
  assigned_stores: [
    {
      storeid: 1,
      store_number: "1",
      store_name: "Store 1",
    },
    {
      storeid: 2,
      store_number: "2",
      store_name: "Store 2",
    },
    {
      storeid: 3,
      store_number: "3",
      store_name: "Store 3",
    },
    {
      storeid: 4,
      store_number: "4",
      store_name: "Store 4",
    },
  ],
  unassigned_stores: [
    {
      storeid: 5,
      store_number: "5",
      store_name: "Store 5",
    },
    {
      storeid: 6,
      store_number: "6",
      store_name: "Store 6",
    },
  ],
};

export const updatedUserStoresResp = {
  error: 0,
  success: true,
  all_stores_for_user: [],
  assigned_stores: [
    {
      storeid: 2,
      store_number: "2",
      store_name: "Store 2",
    },
    {
      storeid: 3,
      store_number: "3",
      store_name: "Store 3",
    },
    {
      storeid: 4,
      store_number: "4",
      store_name: "Store 4",
    },
    {
      storeid: 5,
      store_number: "5",
      store_name: "Store 5",
    },
  ],
  unassigned_stores: [
    {
      storeid: 1,
      store_number: "1",
      store_name: "Store 1",
    },
    {
      storeid: 6,
      store_number: "6",
      store_name: "Store 6",
    },
  ],
};
