import { useAppSelector, useAppDispatch } from "../../../hooks";

/** Flat context selector, same shape as useOrdersCtx/useReceiversCtx. */
export const useSuggestedCtx = () => {
  const dispatch = useAppDispatch();
  const { url, token } = useAppSelector((s) => s.app);
  const { type, singleDate, lastStore, lastGroup, selectedGroup, selectedStore } =
    useAppSelector((s) => s.search);
  const { userid, assignedStores, selectedGroupStores } = useAppSelector(
    (s) => s.user,
  );
  const {
    asOf,
    leadDays,
    coverDays,
    lookbackWeeks,
    groupRows,
    items,
    activeStoreId,
    activeStoreLabel,
    dailyByDepartment,
    notSelling,
    notSellingStatus,
    activeTab,
    parameters,
    coverage,
    requestedStoreIds,
    sheetKey,
    expandedStores,
    loadingGroup,
    loadingItems,
    exportOpen,
    selectedDay,
    storeSearch,
    topDescFilter,
    topDeptFilter,
    nsDescFilter,
    nsUpcFilter,
    upcFilter,
    descFilter,
    actionFilter,
  } = useAppSelector((s) => s.dev.suggested);

  return {
    dispatch,
    url,
    token,
    type,
    singleDate,
    lastStore,
    lastGroup,
    selectedGroup,
    selectedStore,
    userid,
    assignedStores,
    selectedGroupStores,
    asOf,
    leadDays,
    coverDays,
    lookbackWeeks,
    groupRows,
    items,
    activeStoreId,
    activeStoreLabel,
    dailyByDepartment,
    notSelling,
    notSellingStatus,
    activeTab,
    parameters,
    coverage,
    requestedStoreIds,
    sheetKey,
    expandedStores,
    loadingGroup,
    loadingItems,
    exportOpen,
    selectedDay,
    storeSearch,
    topDescFilter,
    topDeptFilter,
    nsDescFilter,
    nsUpcFilter,
    upcFilter,
    descFilter,
    actionFilter,
  };
};
