export const allUsersResp = {
  error: 0,
  success: true,
  msg: "Success",
  users: [
    {
      id: 1,
      username: "test1",
      password: "SomeR@ndomPassword123!",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "one",
      last_name: "test",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: 1,
      role: 5,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 2,
      username: "test2",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "two",
      last_name: "fake",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 3,
      username: "test3",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "three",
      last_name: "example",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: 1,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 4,
      username: "test4",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "four",
      last_name: "notreal",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 5,
      username: "test5",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "five",
      last_name: "who",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
    {
      id: 6,
      username: "test6",
      password: "",
      user_level: 5,
      last_visit: null,
      join_date: null,
      first_name: "six",
      last_name: "Jenkins",
      email: "test@example.com",
      company: 1,
      active: 1,
      template: 1,
      security: null,
      role: null,
      password_change_needed: 0,
      logged_in: 1,
      security_question_id: 1,
      security_answer: "",
    },
  ],
};
