import { useAppDispatch, useAppSelector } from "../../../hooks";

export const useTeamCtx = () => {
  const dispatch = useAppDispatch();
  const { url, token, isDesktop, isTablet } = useAppSelector((state) => state.app);
  const { userid, userLevel, companies } = useAppSelector((state) => state.user);
  const {
    users,
    userInfo,
    refresh,
    selectedUserId,
    selectedUserForm,
    selectedForm,
    userLevels,
    userCompanyIds,
    isDeletingUser,
    userFilterText,
    userFilterType,
    selectedCompanyId,
    availableUsernameText,
    usernameTextColor,
    availableEmailText,
    emailTextColor,
    selectedUserStores,
  } = useAppSelector((state) => state.users);
  const {
    baseGroups,
    selectedBaseGroups,
    company,
    storesWithBGID,
    selectedNewUserStores,
    activeBaseGroups,
    inactiveBaseGroups,
    bgIdsToAssign,
    bgIdsToUnassign,
    userCompany,
  } = useAppSelector((state) => state.baseGroup);

  return {
    dispatch,
    url,
    token,
    isDesktop,
    isTablet,
    userid,
    userLevel,
    companies,
    users,
    userInfo,
    refresh,
    selectedUserId,
    selectedUserForm,
    selectedForm,
    userLevels,
    userCompanyIds,
    isDeletingUser,
    userFilterText,
    userFilterType,
    selectedCompanyId,
    availableUsernameText,
    usernameTextColor,
    availableEmailText,
    emailTextColor,
    selectedUserStores,
    baseGroups,
    selectedBaseGroups,
    company,
    storesWithBGID,
    selectedNewUserStores,
    activeBaseGroups,
    inactiveBaseGroups,
    bgIdsToAssign,
    bgIdsToUnassign,
    userCompany,
  };
};
